FROM python:3.12-slim

ENV PYTHONUNBUFFERED=1

WORKDIR /app

RUN pip install poetry

COPY . /app

RUN poetry config virtualenvs.create false \
    && poetry install --no-interaction --no-ansi


CMD ["poetry", "run", "celery", "-A", "app.celery", "worker", "--loglevel=info"]
